api:
  api_token: ragflow-Y1ZWNiOTk2NjZkMjExZjBhY2NhMDI0Mm
  auth_token: Ijk4YzZjYjE2NjZjZjExZjBhMTkzMDI0MmFjMTQwMGZlIg.aH9F5A.uA5MbSa2r9zwdbs4xJYNBmoHURM
  base_url: http://121.37.88.5:9380
  headers:
    Accept: application/json
    Content-Type: application/json
  timeout: 30
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
output:
  format: table
  max_width: 120
